---
name: Continuous Integration
on: push
 
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2  
          - name: Confirmation
            run: |
              set +e
              gcc --version
              which lcov
              which make
          - name: Setup tools
            run: |
              sudo apt update
              sudo apt install make -y
              sudo apt install lcov -y
              make --version
              lcov --version
    gcov:
        runs-on: ubuntu-latest
        needs: [setup]
        steps:
          - name: Checkout
            uses: actions/checkout@v2  
          - name: Confirmation
            run: |
              set +e
              gcc --version
              which lcov
              which make
          - name: Compile and Link
            run: |
              cd mini-expect
              make
              ls -ltrA
