name: Continuous Integration
on: push
 
jobs:
    gcov:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2  
          - name: Preparation
            run: |
              gcc --version
              which lcov
              which make
          - name: Compile and Link
            run: |
              cd mini-expect
              make
              ls -ltrA
