---
name: Continuous Integration
on: push
 
jobs:
    gcov:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            id: checkout
            uses: actions/checkout@v2  
          - name: Confirmation
            id: confirmation
            run: |
              set +e
              gcc --version
              which lcov
              which make
          - name: Setup tools
            id: setup-tools
            run: |
              sudo apt update
              sudo apt install make -y
              sudo apt install lcov -y
              make --version
              lcov --version
          - name: Compile and Link
            id: compile-and-link
            run: |
              #! Makefile が配置されているディレクトリに移動する
              cd mini-expect
              pwd
              make clean
              make COV=gcov
              ls -ltrA
          - name: Execute GcovProgram
            id: execute-gcovprogram
            run: |
              #! Makefile が配置されているディレクトリに移動する (step を跨ぐとカレントディレクトリが元にもどる)
              cd mini-expect
              #! プログラムを実行する
              ./mini_expect ls -1
              #! カバレッジ率を算出する (*.gcda)
              find . -type f -name "*.gcda" | xargs -I@ gcov -b @ | tee -a gcov.log
              #! lcov を使って *.info を生成する
              lcov --rc lcov_branch_coverage=1 -c -d . -o tmp.info
              #! /usr/include/ を計測対象外にする (tmp.info から output.info を作る)
              lcov --rc lcov_branch_coverage=1 -b -c -d . -r tmp.info  '/usr/include/*' -o output.info
              #! genhtml を使って *.info から HTML を生成する
              genhtml --branch-coverage -o OUTPUT -p . -f output.info 
              #! OUTPUT を zip にする
              zip -r -9 OUTPUT.zip OUTPUT gcov.log

